application:
  title: '@project.name@'
  version: '@project.version@'
logging:
  file:
    name: './target/site/logs/lottoland-challenge.log'
#    path: '/tmp/log'
#    path: './target/logs/'
  general:
    level: INFO
  level:
    com:
      batyuta:
        challenge:
          lottoland: ${logging.general.level}
    org:
      springframework: ${logging.general.level}
  pattern:
    file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t]%X{_from} %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) ${PID:- } --- [%t]%clr(%X{_from}){blue} %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  error:
    path: /exception
    whitelabel:
      enabled: false
spring:
  data:
    rest:
      base-path: /api
  jpa:
    open-in-view: false
  messages:
    basename: messages/messages
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://example.com/.well-known/jwks.json
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 12h
